{% set name = "snowflake.core" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('.', '_') }}-{{ version }}.tar.gz
  sha256: 1083a01884e9cceb93dc075c99bbc9ae9d7afd808bf3cff8c003624d35f119d0

build:
  # allows SF to rebuild the package as needed without incurring a
  # higher build number than the package we release
  number: 100
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - certifi
    - pydantic >=2
    - python-dateutil >=2.8.2
    - requests
    - snowflake-connector-python
    - pyyaml
    - urllib3
  run_constrained:
    - snowflake-snowpark-python >=1.5.0,<2.0.0

# Due to following error, test_simple_file_logging has started to be flaky in CI. Please check it during the next version update
# E PermissionError: [Errno 13] Permission denied: '/tmp/snowflake_core.log'
{% set deselect_tests = "--deselect=tests/unit/test_logging.py::test_simple_file_logging" %}

test:
  imports:
    - snowflake.core
  source_files:
    - tests
  commands:
    - pip check
    # 1. do not test tests/integ because
    #    we do not have CONNECTION_PARAMETERS set
    # 2. tests/unit/test_common.py rely on paths relative to the test source file location
    #    PROJECT_SRC = Path(__file__).parent.parent.parent / "src" / "snowflake" / "core"
    - pytest tests/unit -m "not snowpark" --ignore=tests/unit/test_common.py {{ deselect_tests }}
  requires:
    - pip
    - pytest

about:
  home: https://pypi.org/project/snowflake.core
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Snowflake Python API for Resource Management
  description: Snowflake Python API for Resource Management
  doc_url: https://docs.snowflake.com/developer-guide/snowflake-python-api/snowflake-python-overview
  dev_url: https://pypi.org/project/snowflake.core

extra:
  recipe-maintainers:
    - lorepirri
