{% set name = "snowflake.core" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/snowflake_core-{{ version }}.tar.gz
  sha256: 8bf267ff1efcd17f157432c6e24f6d2eb6c2aeed66f43ab34b215aa76d8edf02

build:
  # allows SF to rebuild the package as needed without incurring a
  # higher build number than the package we release
  number: 100
  # atpublic doesn't support py>311
  # snowflake-connector-python not available for s390x
  skip: true  # [py<38 or py>311 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - atpublic >=4
    - pydantic >=2
    - python-dateutil >=2.8.2
    - requests
    - snowflake-connector-python
    - pyyaml
    - urllib3
  run_constrained:
    - snowflake-snowpark-python >=1.5.0,<2.0.0

test:
  imports:
    - snowflake.core
  requires:
    - pip
    - pytest
  source_files:
    - tests/unit
  commands:
    - pip check
    # do not test tests/integ because
    # we do not have CONNECTION_PARAMETERS set
    - pytest tests/unit -m "not snowpark"

about:
  home: https://pypi.org/project/snowflake.core
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Snowflake Python API for Resource Management
  description: Snowflake Python API for Resource Management
  doc_url: https://docs.snowflake.com/developer-guide/snowflake-python-api/snowflake-python-overview
  dev_url: https://pypi.org/project/snowflake.core

extra:
  recipe-maintainers:
    - lorepirri
